# Generated by Django 6.1 on 2026-08-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('transmission_type', models.CharField(choices=[('MANUAL', 'Manual Only'), ('AUTOMATIC', 'Automatic Only'), ('BOTH', 'Both Manual & Automatic')], default='BOTH', max_length=10)),
                ('profile_photo', models.ImageField(upload_to='drivers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='drivers.driver')),
            ],
        ),
    ]
