# Generated by Django 6.1 on 2026-08-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('pickup_address', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('duration_hours', models.PositiveIntegerField(default=4)),
                ('car_transmission', models.CharField(choices=[('MANUAL', 'Manual Only'), ('AUTOMATIC', 'Automatic Only'), ('BOTH', 'Both Manual & Automatic')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='drivers.driver')),
            ],
        ),
    ]
